# Generated by Django 4.1.1 on 2022-09-20 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electric',
            fields=[
                ('date_electric_start', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('date_electric_end', models.DateField(unique=True)),
                ('room_A', models.IntegerField()),
                ('room_B', models.IntegerField()),
                ('room_CShare', models.IntegerField()),
                ('room_D', models.IntegerField()),
                ('room_E', models.IntegerField()),
                ('room_F', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('date_gas_start', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('date_gas_end', models.DateField(unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('date_water_start', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('date_water_end', models.DateField(unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('date_room', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('A', models.CharField(max_length=255, null=True)),
                ('B', models.CharField(max_length=255, null=True)),
                ('C', models.CharField(max_length=255, null=True)),
                ('D', models.CharField(max_length=255, null=True)),
                ('E', models.CharField(max_length=255, null=True)),
                ('F', models.CharField(max_length=255, null=True)),
                ('G', models.CharField(max_length=255, null=True)),
                ('H', models.CharField(max_length=255, null=True)),
                ('I', models.CharField(max_length=255, null=True)),
                ('J', models.CharField(max_length=255, null=True)),
                ('K', models.CharField(max_length=255, null=True)),
                ('amount_electric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator_app.electric')),
                ('amount_gas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator_app.gas')),
                ('amount_water', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator_app.water')),
            ],
        ),
    ]
