---
- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Restart and enable nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes